stages:
  - build
  - integration
  - test
  - review
  - deploy

build-lib:
  image: node:10-alpine
  stage: build
  script:
    - npm ci
    - npm run build:lib
  artifacts:
    expire_in: 1 week
    paths:
      - dist/@w11k/angular-sticky-things

build-demo-master:
  image: node:10-alpine
  stage: integration
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/angular-sticky-things-demo
  only:
    refs:
      - master
      - develop


build-demo-review:
  image: node:10-alpine
  stage: integration
  script:
    - npm ci
    - npm run build  -- --base-href /angular-sticky-things/$CI_COMMIT_REF_NAME/
  artifacts:
    expire_in: 1 week
    paths:
      - dist/angular-sticky-things-demo
  except:
    - master
    - develop

#
#test-lib:
#  image: trion/ng-cli-karma
#  stage: test
#  script:
#  - npm run test:lib
#
#test-demo:
#  image: trion/ng-cli-karma
#  stage: test
#  script:
#  - npm run test

#test-demo:
#  image: weboaks/node-karma-protractor-chrome
#  stage: test
#  script:
#  - npm install -g npm@latest
#  - npm ci
#  - npm run e2e



publish-review:
  image: node:10
  stage: review
  script:
    - npx gh-pages -e review/$$CI_COMMIT_REF_NAME -d dist/angular-sticky-things-demo
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://w11k.github.io/angular-sticky-things/review/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master
    - develop

#publish-demo:
#  image: node:10
#  stage: review
#  script:
#    - npx gh-pages -e review/$$CI_COMMIT_REF_NAME -d dist/angular-sticky-things-demo
#  environment:
#    name: review/$CI_COMMIT_REF_NAME
#    url: https://w11k.github.io/angular-sticky-things/review/$CI_COMMIT_REF_NAME
#  only:
#    - branches
#  except:
#    - master
#    - develop


publish:
  image: node:10-alpine
  stage: deploy
  only:
    - tags
  script:
    - cd dist/@w11k/angular-sticky-things
    - cp ../../../README.md .
    - cp ../../../LICENSE .
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --access=public


